### PR TITLE
[WIP] Classic Support

### PR DESCRIPTION
**Pull request by pctD**
Hi!

I've been working on supporting Classic for this fantastic Addon. I was able to get AdiButtonAuras running and basically fully featured for Hunter.

This PR does the following:
- Add dependency on LibClassicDurations to improve aura handling (show time left).
- Remove dependency on LibDualSpec.
- Remove all BFA related code/events that don't exist in Classic.
- Fixes some issues with Shaman totem tracking (due to totems having different suffixes, eg. `Searing Totem II` for Rank 2).

Things that are still broken:
- Masque support needs to be fixed. Right now if it's ticked it just fades out all the buttons and doesn't really work. Haven't started debugging that.

TODO:
- Implement/fix every other class. Finish Shaman.

### CODE REVIEW

**Comment by Rainrider** [comment]
I can't accept your pull request in it's current form since we release live versions from this repo and you are basically removing support for 8.x.

Maybe it would be a better idea to fork as a separate addon for classic, especially since the rules sections and some of the dependencies will diverge.

If you would like, maybe @Adirelle could add you to the org and create a fork for you to merge your work.

**Comment by Rainrider** [comment]
Btw have you tested interrupts? I haven't (and probably won't) played classic but I thought that cast related events are different there

**Comment by pctD** [comment]
Thanks for your comments. I'm well aware these won't be able to merged into master, and I put some more comments in the issue I created. (https://github.com/AdiAddons/AdiButtonAuras/issues/333)

With your (or Adirelle's) blessing I will continue to develop the classic versions of these addons/libraries in my personal forks, and we can talk about merging them into a classic branch or specific classic repos later down the line. I will close the PRs, but leave the issue open and link to my forks instead.

**Comment by Rainrider** [comment]
I think all of Adi's addons are GPL, so given that, do what suits you best imo.

**Pull request closed without merging**
